# Site configuration
repository: FSAdministrator/FSAdministrator.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Felix Saville
title: Systems Administrator
email: savillefelix2@gmail.com
website: https://fsadministrator.github.io/

# Dark Mode configuration
darkmode: true

# Social links configuration
github_username: FSAdministrator
facebook_username: FelixSaville
instagram_username: felix_saville
linkedin_username: felixsaville

# About Section configuration
about_content: |
  Hello there! I'm Felix, a Systems Engineer at mb3, bringing over 5 years of experience to the ever-evolving world of Information Technology.

  My journey through IT has equipped me with technical knowledge across several key areas. My experience spans <mark>Automation Development (PowerShell, Rust API, Python)</mark>, <mark>Website Design (PHP, JavaScript, HTML + CSS)</mark>, <mark>Infrastructure Management (On-Site, Azure, Google, Hybrid)</mark>, and <mark>Device Deployment (JAMF, Intune)</mark>.

  These technical skills have also allowed me to develop <mark>client management skills</mark>, <mark>professional communication</mark>, <mark>simplifying complex system problems</mark>, and <mark>maintaining good relationships</mark> with clients and colleagues.

  Beyond my career, I'm committed to a balanced lifestyle. Hitting the gym, enjoying pickleball, playing Magic: The Gathering at card shops, or diving into video games are activities that are good for my well-being and social battery!

  Finally, my passion for technology doesn't stop at 5 pm; I'm always on the lookout for the latest technology trends, as it's a personal interest that keeps me engaged. My dedication to both my career and personal growth is what fuels my continuous advancement in the world of IT.
  
# Main content configuration
content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Timberlands Website Rebuild
        quote: "March 2020 - November 2020"
        description: |
          Led a strategic in-house rebuild of the Timberlands website as part of my KPI's, transforming it into a cost-effective, self-managed platform. Collaborated closely with a colleague to enhance user experience, leveraging Drupal on an on-site Virtual Machine. Focused on developing a user-friendly GUI for both visitors and editors, ensuring accessibility and efficiency.

      - layout: top-middle
        title: Asset Management System Implementation
        quote: "May 2021 - July 2021"
        description: |
          Led the introduction of an asset management system at Timberlands, conducting a cost-benefit analysis to secure managerial support. Selected and implemented SNIPE-IT, a robust, open-source solution tailored for IT teams. This project allowed me to perfect my technical expertise in PHP, Java, CSS, and REST APIs, significantly enhancing digital asset management and future IT support capabilities.

      - layout: top-middle
        title: Company-Wide Laptop Rollout
        quote: "July 2021 - December 2021"
        description: |
          Took on a laptop rollout to support Timberlands' transition to remote work during challenges such as chip shortages and global pandemic-related delays. Managed all aspects of the rollout, including procurement, cybersecurity training, deployment, and helpdesk support. This project allowed me to execute complex IT initiatives under pressure, ensuring business continuity and enhancing remote work capabilities.

      - layout: top-middle
        title: Proxmox VM Private-Cloud Deployment
        quote: "Specific Date/Range"
        description: |
          Fully set up, deployed, and configured a virtual sandbox and production environment utilizing local hardware to host various in-house applications like Bitwarden through Docker, Windows Servers, Bookstack, and other solutions. This project demonstrated my ability to leverage Proxmox VM technology for efficient virtualization management and deployment, ensuring robust, scalable, and secure IT infrastructure for the company.

      - layout: top-middle
        title: Cloud Platform Automations
        quote: "Specific Date/Range"
        description: |
          Utilized PowerShell to create and manage a comprehensive user creation, update, and deletion platform, integrating school SMS data with platforms like Microsoft, Google, and Apple School Manager. This automation project facilitated seamless inter-platform communication and management, showcasing my expertise in scripting and automation to optimize IT operations and user account management across multiple cloud services.

      - layout: top-middle
        title: Access 4 Deployment
        quote: "Specific Date/Range"
        description: |
          Leveraged my knowledge of VOIP technology to deploy various phone system setups with schools and businesses across the Bay of Plenty using Webex, Teams, and UCXpress. This solution allowed me to delve into and master VOIP deployment, offering advanced communication solutions that enhanced collaboration and connectivity for our clients.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Timberlands Limited
        link: https://tll.co.nz/
        sub_title: IT Support Specialist
        caption: October 2019 - March 2022
        quote: "We commit to being the best and safest production forest in the world, Mo ake tonu atu."
        description: |
            Originally joined Timberlands as an IT Support Specialist, rapidly learning the organization's IT infrastructure, focusing on optimizing day-to-day operations. Key accomplishments include mastering the complex platform Citrix, a private cloud structure, enhancing control and support for the IT team and staff, and providing exceptional support to users, both onsite and remotely, while maintaining efficiency and user satisfaction.

      - layout: left
        title: Spark Rotorua
        link: https://www.spark.co.nz/
        sub_title: Sales Consultant
        caption: November 2018 - March 2019
        quote: "The best hands-on experience is front-facing all types of customers, assisting NZ in the digital world."
        description: |
            At Spark, a leader in telecommunications and digital services, provided support to customers as a Sales Consultant. Responsibilities/achievements included providing detailed consults on devices and digital services to a large number of customers across NZ, finding effective and accurate solutions while providing excellent customer support, and greatly exceeding sales targets by selling 60 solutions within a single month.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Avonmore / EmployNZ
        caption: February 2016 - November 2018
        sub_title: Diploma in Systems Administration (Level 6)
        quote: >
          EmployNZ helped me learn a lot around System Deployment and Management, and I couldn't of done IT without their Hands-On Teaching.
        description: |
          During my time at EmployNZ, I learnt most of my key skills that I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at EmployNZ and learnt a lot about different Types of Operating Systems, platforms, and programming Languages.

# Footer configuration
footer_show_references: true
references_title: Contact Me For More Information + References!

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
